Default gasprice + new rpc methods
ethereum/pyethapp pull request #179
Opened 2016-11-12 05:34 UTC by hackaugusto

- geth will ignore a transaction with a low gasprice and blacklist the
user, this caused trouble because the default gasprice used in the
deploy_solidity_contract method was 1 wei.
- pooling didn't account for the removal of a transaction (that can be
caused by the low gas price)
- added new rpc methods:
  - eth_estimateGas
  - eth_getTransactionReceipt
  - eth_getCode
- added a utility for the Proxy to get the estimated gas usage.

2016-11-18 22:07 UTC, LefterisJP commented
@heikoheiko Can we get this PR merged ASAP? If this PR is not in place one of the raiden integration tests fail:

`raiden/tests/integration/test_blockchainservice.py::test_new_netting_contract`

2016-12-10 00:51 UTC, ezdac requested changes
include return value and error distinction to `poll` method

2016-12-10 00:51 UTC, ezdac commented on pyethapp/rpc_client.py
`return True` or `return block_number`
at this point the transaction was successful

2016-12-10 00:51 UTC, ezdac commented on pyethapp/rpc_client.py
> +                    raise Exception('invalid transaction, check gas price')
distinguish exeptions (e.g. `raise InvalidTransaction`)

2016-12-10 00:51 UTC, ezdac commented on pyethapp/rpc_client.py
> +            raise Exception('timeout when polling for transaction')
distinguish Exeptions (e.g. `raise PollTimeoutException`)

2016-12-19 11:33 UTC, hackaugusto commented on pyethapp/rpc_client.py
Now returning the current block number, this will include the confirmations block.

2016-12-20 20:08 UTC, ezdac approved these changes
Looks good to me.

2017-01-23 21:30 UTC, merged